# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1l9AvQJegvI-gOJ3_uEMnOIp9EBlFzOfb
"""



"""# 1)Find the minimum and maximum element in an array."""

a=[31,5,15,91,17.40]
print(max(a))
print(min(a))

"""# 2)arr[] = {1,5,3,2}
Given a random set of numbers, print them in sorted order
"""

arr={1,5,3,2}
print(sorted(arr))

"""# 3)write a program to reverse the array"""

arr=["apple","banana","cherry","mango"]
arr.reverse()
print(arr)

"""# 4)Find the smallest and largest element In an array"""

arr=[3,7,16,35,8,4]
print("smallest",min(arr))
print("largest",max(arr))

"""# 5)create three arrays and find the common element in these array"""

l1 = [4, 9, 1, 17, 11, 26, 28, 54, 69]
l2 = [9, 9, 74, 21, 45, 11, 63, 28, 26]
l3 = [5, 8, 3, 9, 10, 26,11]
s=set(l1).intersection(l2).intersection(l3)
print(list(s))

"""# 6)Find the factorial of a number using array"""

def factorial(n):
 fact=1
 for i in range(1,n+1):
   fact*=i
 return fact
arr=[1,3,5,7,9]
factorial=[factorial(x) for x in arr]
print("factorial:",factorial)